name: Android Lint
on:
  push:
jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-18.04
    container: mobileposse/dev:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Lint
        run: ./gradlew testReleaseUnitTest
          continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step
#        uses: mobileposse/github-android-lint-action@v1
#        with:
#          repo_token: ${{ secrets.GITHUB_TOKEN }}
#          filename: [filename goes here]
#          report_name: 'Gradle Lint Results'